version: '3'
services:
  postgres:
    image: postgres:16
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: unless-stopped

  pgadmin:
    image: dpage/pgadmin4
    depends_on:
      - postgres
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: pgadmin@vivantehealth.interview
      PGADMIN_DEFAULT_PASSWORD: pgadmin
    restart: unless-stopped
    
  dbt:
    build:
      context: .
    entrypoint: ["tail", "/dev/null", "-f"]
    volumes:
      - $PWD:/dbt
    depends_on:
      - postgres
    ports:
      - "8080:8080"


volumes:
  postgres-data:
